base/urls.py
from django.urls import path

comments/urls.py
from django.urls import path

from comments.apps import CommentsConfig
from comments.views import CommentUpdateView, CommentCreateView, CommentDeleteView

app_name = CommentsConfig.name

urlpatterns = [
    path(
        "create/<int:pk>/", CommentCreateView.as_view(), name="comment_create"
    ),  # создание комментария
    path(
        "update/<int:pk>/",
        CommentUpdateView.as_view(),
        name="comment_update",
    ),  # редактирование комментария
    path(
        "delete/<int:pk>/",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),  # удаление комментария
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "", include("publications.urls", namespace="publications")
    ),  # маршрутизация к публикациям
    path(
        "users/", include("users.urls", namespace="users")
    ),  # маршрутизация к пользователям
    path(
        "comments/", include("comments.urls", namespace="comments")
    ),  # маршрутизация к комментариям
    path(
        "codes/", include("codes.urls", namespace="codes")
    ),  # маршрутизация к кодам верификации
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path

from publications.apps import PublicationsConfig
from publications.views import (
    PublicationListView,
    PublicationDetailView,
    PublicationCreateView,
    PublicationUpdateView,
    PublicationDeleteView,
    AddRemoveLike,
    PublicationOwnerListView,
)

app_name = PublicationsConfig.name

urlpatterns = [
    path(
        "", PublicationListView.as_view(), name="publication_list"
    ),  # список публикаций
    path(
        "owner_pub/", PublicationOwnerListView.as_view(), name="owner_pub"
    ),  # вывод списка собственных публикаций
    path(
        "view/<int:pk>/", PublicationDetailView.as_view(), name="publication_view"
    ),  # просмотр одной публикации
    path(
        "create/", PublicationCreateView.as_view(), name="publication_create"
    ),  # создание публикации
    path(
        "update/<int:pk>/",
        PublicationUpdateView.as_view(),
        name="publication_update",
    ),  # редактирование публикации
    path(
        "delete/<int:pk>/",
        PublicationDeleteView.as_view(),
        name="publication_delete",
    ),  # удаление публикации
    path(
        "<int:pk>/like/", AddRemoveLike.as_view(), name="like"
    ),  # установить/удалить лайк
]

comments/models.py
from django.db import models

from config.settings import AUTH_USER_MODEL, NULLABLE
from publications.models import Publication


class Comment(models.Model):
    """Модель для комментария к публикации"""

    publication = models.ForeignKey(
        Publication,
        on_delete=models.CASCADE,
        verbose_name="Публикация",
        related_name="comments",
        **NULLABLE,
    )
    author = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор", **NULLABLE
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата и время создания",
    )
    text = models.TextField(verbose_name="Текст", **NULLABLE)

    def __str__(self):
        return f"Комментарий от {self.author} к публикации {self.publication}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ["id"]

comments/forms.py
from django import forms

from comments.models import Comment


class CommentForm(forms.ModelForm):
    """Класс для описания формы комментария"""

    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Введите текст комментария",
                "rows": 5,
            }
        )
    )

    class Meta:
        model = Comment
        fields = ("text",)

comments/views.py
from django.views.generic import CreateView, UpdateView, DeleteView

from comments.forms import CommentForm
from comments.models import Comment
from publications.models import Publication
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin


class BaseCommentView:
    """Базовый класс для всех контроллеров"""

    model = Comment

    def get_success_url(self):
        """Метод определяет ссылку на публикацию, к которой привязан комментарий"""
        publication = Publication.objects.get(pk=self.object.publication.pk)
        return reverse(
            "publications:publication_view", args=[str(self.object.publication.pk)]
        )


class CommentCreateView(BaseCommentView, CreateView, LoginRequiredMixin):
    """Контроллер для создания комментария"""

    form_class = CommentForm

    def form_valid(self, form):
        """Автоматическая привязка к комментарию автора и публикации"""
        form.instance.author = self.request.user
        form.instance.publication = Publication.objects.get(pk=self.kwargs.get("pk"))
        return super().form_valid(form)


class CommentUpdateView(BaseCommentView, UpdateView, LoginRequiredMixin):
    """Контроллер для редактирования комментария"""

    form_class = CommentForm
    template_name = "comments/comment_form.html"
    extra_context = {"title": "Редактировать комментарий"}


class CommentDeleteView(BaseCommentView, DeleteView, LoginRequiredMixin):
    """Контроллер для удаления комментария"""

    template_name = "comments/comment_confirm_delete.html"
    extra_context = {"title": "Удалить комментарий"}

comments/templates/comments/comment_confirm_delete.html
{% extends 'base/base.html' %}
{% block title %}Удаление комментария{% endblock title %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h3>Удаление комментария</h3>
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card col-6">
                    <p class="card-text">
                    <p>Действительно хотите удалить</p>
                    <p><b>{{object.name}}</b></p>
                    </p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>

                    <!-- Кнопки -->
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <button type="submit" class="btn btn-outline-danger ml-5 px-2 pb-md-2 mx-2" role="button">
                            Удалить
                        </button>
                        <a class="btn btn-outline-primary px-2 pb-md-2 mx-2"
                           href="{% url 'publications:publication_view' pk=object.publication.pk %}"
                           role="button">Отменить</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

comments/templates/comments/comment_form.html
{% extends 'base/base.html' %}
{% block title %}Редактирование комментария{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <h3>Редактирование комментария</h3>
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.text }}
                    </div>

                    <!-- Кнопки -->
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <button type="submit" class="btn btn-outline-success ml-5 px-2 pb-md-2 mx-2" role="button">
                            Сохранить
                        </button>
                        <a class="btn btn-outline-primary px-2 pb-md-2 mx-2"
                           href="{% url 'publications:publication_view' pk=object.publication.pk %}"
                           role="button">Назад</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

comments/templates/comments/comments.html
{% load my_tags %}
<!-- Карточка комментариев -->
<div class="card mb-3">
    <!-- Добавить новый комментарий -->
    {% if user.is_authenticated %}
    <div class="card-heater">
        <div class="row">
            <h5 class="mt-3 mb-3">Добавить комментарий:</h5>
            <form method="post" enctype="multipart/form-data"
                  action="{% url 'comments:comment_create' pk=publication.pk %}">
                {% csrf_token %}
                {{ comment_form.text }}
                <button class="btn btn-outline-primary mt-3" type="submit">Отправить</button>
            </form>
        </div>
    </div>
    {% endif %}

    <!-- Список комментариев -->
    <div class="card-body">
        <h4 class="mt-3 mb-3">Комментарии пользователей:</h4>
        {% if comments %}
        <div class="row">
            <h5 class="card-title">Количество комментариев: {{comments.count}}</h5>
            {% for comment in comments %}
            <div class="card mb-3">
                <!-- Мета данные -->
                <div class="card-header">
                    <ul class="list-group list-group-horizontal">
                        {% if comment.author.avatar %}
                        <img class="img-fluid" src="{{ comment.author.avatar | media_filter}}" width="40px">
                        {% endif %}
                        <li class="list-group-item">
                            <span>{{ comment.author.nickname }}</span>
                        </li>
                        <li class="list-group-item">
                            {{comment.created_at}}
                        </li>
                    </ul>
                </div>
                <!-- Содержание комментария -->
                <div class="card-body">
                    <p class="card-text">{{ comment.text }}</p>
                </div>
                <!-- Кнопки и дата -->
                <div class="card-footer">
                    {% if user == comment.author or user.is_superuser %}
                    <a class="btn btn-outline-primary" href="{% url 'comments:comment_update' comment.pk %}"
                       role="button">Редактировать</a>
                    <a class="btn btn-outline-danger" href="{% url 'comments:comment_delete' comment.pk%}"
                       role="button">Удалить</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}

        </div>
        {% else %}
        <p>Нет комментариев</p>
        {% endif %}
    </div>
</div>