base/urls.py
from django.urls import path

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "", include("publications.urls", namespace="publications")
    ),  # маршрутизация к публикациям
    path(
        "users/", include("users.urls", namespace="users")
    ),  # маршрутизация к пользователям
    path(
        "comments/", include("comments.urls", namespace="comments")
    ),  # маршрутизация к комментариям
    path(
        "codes/", include("codes.urls", namespace="codes")
    ),  # маршрутизация к кодам верификации
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path

from publications.apps import PublicationsConfig
from publications.views import (
    PublicationListView,
    PublicationDetailView,
    PublicationCreateView,
    PublicationUpdateView,
    PublicationDeleteView,
    AddRemoveLike,
    PublicationOwnerListView,
)

app_name = PublicationsConfig.name

urlpatterns = [
    path(
        "", PublicationListView.as_view(), name="publication_list"
    ),  # список публикаций
    path(
        "owner_pub/", PublicationOwnerListView.as_view(), name="owner_pub"
    ),  # вывод списка собственных публикаций
    path(
        "view/<int:pk>/", PublicationDetailView.as_view(), name="publication_view"
    ),  # просмотр одной публикации
    path(
        "create/", PublicationCreateView.as_view(), name="publication_create"
    ),  # создание публикации
    path(
        "update/<int:pk>/",
        PublicationUpdateView.as_view(),
        name="publication_update",
    ),  # редактирование публикации
    path(
        "delete/<int:pk>/",
        PublicationDeleteView.as_view(),
        name="publication_delete",
    ),  # удаление публикации
    path(
        "<int:pk>/like/", AddRemoveLike.as_view(), name="like"
    ),  # установить/удалить лайк
]

publications/models.py
from django.db import models

from config.settings import AUTH_USER_MODEL, NULLABLE


class Publication(models.Model):
    """Модель для публикации"""

    title = models.CharField(
        max_length=150,
        verbose_name="Заголовок",
        help_text="Введите заголовок публикации",
    )
    body = models.TextField(
        verbose_name="Содержимое", help_text="Введите содержимое статьи"
    )
    preview = models.ImageField(
        upload_to="publications/photo",
        verbose_name="Изображение",
        help_text="Добавьте изображение",
        **NULLABLE,
    )
    slug = models.CharField(max_length=150, verbose_name="Slug", **NULLABLE)
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name="Платная публикация",
    )
    views_count = models.PositiveIntegerField(
        default=0, editable=False, verbose_name="Просмотры"
    )
    author = models.ForeignKey(
        AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор", **NULLABLE
    )
    liked_by = models.ManyToManyField(
        AUTH_USER_MODEL,
        verbose_name="Пользователи, которые поставили лайк",
        related_name="liked_posts",
    )

    def __str__(self):
        return f"{self.title} {self.created_at}"

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"
        ordering = ["-id"]

publications/forms.py
from django import forms

from publications.models import Publication


class StyleFormMixin:
    """Миксин для стилизации формы"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_paid":
                field.widget.attrs["class"] = "form-control"


class PublicationForm(StyleFormMixin, forms.ModelForm):
    """Класс для описания формы публикации"""

    class Meta:
        model = Publication
        fields = (
            "title",
            "body",
            "preview",
            "is_paid",
        )

publications/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from comments.forms import CommentForm
from config.settings import NUMBER_OF_PUBLICATION_ON_PAGE
from publications.forms import PublicationForm
from publications.models import Publication
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin


class PublicationListView(ListView):
    """Контроллер для списка публикаций"""

    paginate_by = NUMBER_OF_PUBLICATION_ON_PAGE
    model = Publication
    extra_context = {"title": "Публикации", "back_to_top": True}

    def get_queryset(self, *args, **kwargs):
        """Запрет просмотр платного контента без подписки"""

        queryset = super().get_queryset(*args, **kwargs)
        # Условие: пользователя нет в БД или не имеет подписку
        if not self.request.user.pk or not self.request.user.is_sub:
            queryset = queryset.exclude(is_paid=True)
        return queryset


class PublicationOwnerListView(ListView):
    """Контроллер для списка своих публикаций"""

    paginate_by = NUMBER_OF_PUBLICATION_ON_PAGE
    model = Publication
    extra_context = {"title": "Мои публикации", "back_to_top": True}

    def get_queryset(self, *args, **kwargs):
        """Возвращает список публикаций, для которых пользователь является автором"""

        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        queryset = queryset.filter(author=user)
        return queryset


class PublicationDetailView(DetailView):
    """Контроллер для детального просмотра публикаций"""

    model = Publication
    extra_context = {"title": "Публикации"}

    def get_object(self, queryset=None):
        """Счетчик просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save(update_fields=["views_count"])
        return self.object

    def get_context_data(self, **kwargs):
        """Добавляем форму комментария"""
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()
        return context


class PublicationCreateView(CreateView, LoginRequiredMixin):
    """Контроллер создания публикации"""

    model = Publication
    form_class = PublicationForm
    extra_context = {"title": "Создать публикацию"}
    success_url = reverse_lazy("publications:publication_list")

    def form_valid(self, form):
        """Автоматическая привязка автора к публикации и формирование slug"""
        publication = form.save()
        user = self.request.user
        publication.author = user
        publication.slug = slugify(publication.title)
        publication.save()
        return super().form_valid(form)


class PublicationUpdateView(UpdateView, LoginRequiredMixin):
    """Контроллер изменения публикации"""

    model = Publication
    form_class = PublicationForm
    extra_context = {"title": "Изменить публикацию"}
    success_url = reverse_lazy("publications:publication_list")

    def form_valid(self, form):
        """формирование slug"""
        publication = form.save()
        publication.slug = slugify(publication.title)
        publication.save()
        return super().form_valid(form)

    def get_success_url(self):
        """Перенаправление на нужное сообщение после редактирования"""

        return reverse("publications:publication_view", args=[self.kwargs.get("pk")])


class PublicationDeleteView(DeleteView, LoginRequiredMixin):
    """Контроллер удаления публикации"""

    model = Publication
    extra_context = {"title": "Удалить публикацию"}
    permission_required = "publications.publication_delete"
    success_url = reverse_lazy("publications:publication_list")


class AddRemoveLike(View, LoginRequiredMixin):
    """Контроллер для лайка"""

    def post(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Publication, pk=pk)
        # автор публикации не может поставить себе лайк
        if post.author.id != request.user.id:
            if not post.liked_by.filter(id=request.user.id).exists():
                """если пользователь еще не ставил лайк"""
                post.liked_by.add(request.user)
                post.save()
                return HttpResponseRedirect(
                    reverse("publications:publication_view", args=[str(pk)])
                )
            else:
                """если пользователь уже ставил лайк"""
                post.liked_by.remove(request.user)
                post.save()
                return HttpResponseRedirect(
                    reverse("publications:publication_view", args=[str(pk)])
                )

        return HttpResponseRedirect(
            reverse("publications:publication_view", args=[str(pk)])
        )

publications/templates/publications/publication_confirm_delete.html
{% extends 'base/base.html' %}
{% block title %}Удаление публикации{% endblock title %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card col-6">
                    <p class="card-text">
                    <p>Действительно хотите удалить</p>
                    <p><b>{{object.name}}</b></p>
                    </p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>

                    <!-- Кнопки -->
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <button type="submit" class="btn btn-outline-danger ml-5 px-2 pb-md-2 mx-2" role="button">
                            Удалить
                        </button>
                        <a class="btn btn-outline-primary px-2 pb-md-2 mx-2"
                           href="{% url 'publications:publication_list' %}"
                           role="button">Отменить</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

publications/templates/publications/publication_detail.html
{% extends 'base/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

<!-- Карточка публикации -->
<div class="card mb-3">
    <div class="card-header">
        <!-- Заголовок -->
        <h3 class="card-title">{{ object.title }}</h3>

        <!-- Мета данные -->
        <ul class="list-group list-group-horizontal">
            {% if object.author.avatar %}
            <img class="img-fluid" src="{{ object.author.avatar | media_filter}}" width="40px">
            {% endif %}
            <li class="list-group-item">
                {{ object.author.nickname }}
            </li>
            <li class="list-group-item">
                {{object.created_at}}
            </li>
            {% if object.is_paid %}
            <li class="list-group-item">
                <img class="img-fluid" src="{% static 'img/paid_publication.png' %}" width="30px">
            </li>
            {% endif %}
        </ul>
    </div>

    <!-- Содержание публикации -->
    <div class="card-body">
        <!-- Изображение -->
        {% if object.preview %}
        <img src="{{ object.preview | media_filter}}" class="figure-img img-fluid rounded" width="400px">
        {% endif %}
        <p class="card-text">{{ object.body }}</p>
    </div>

    <div class="card-footer">
        <!-- Отображение просмотров и лайков -->
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">
                <img class="img-fluid" src="{% static 'img/views.png' %}" width="25px">
                <b>{{ object.views_count }}</b>
            </li>
            <!-- Поставить / удалить лайк -->
            {% if user.is_authenticated %}
            <li class="list-group-item">
                <form method="post" action="{% url 'publications:like' object.pk %}">
                    {% csrf_token %}
                    <button style="background: transparent; border: none; box-shadow: none;" type="submit">
                        <img class="img-fluid" src="{% static 'img/likes.png' %}" width="20px">
                        <span>{{ object.liked_by.all.count }}</span>
                </form>
            </li>
            {% else %}
            <li class="list-group-item">
                <img class="img-fluid" src="{% static 'img/likes.png' %}" width="20px">
                <b>{{ object.liked_by.all.count }}</b>
            </li>
            {% endif %}
            <!-- Кнопки -->
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a class="btn btn-outline-primary" href="{% url 'publications:publication_list' %}"
                   role="button">Назад</a>
                {% if user == object.author or user.is_superuser %}
                <a class="btn btn-outline-primary" href="{% url 'publications:publication_update' object.pk %}"
                   role="button">Редактировать</a>
                <a class="btn btn-outline-danger" href="{% url 'publications:publication_delete' object.pk %}"
                   role="button">Удалить</a>
                {% endif %}
            </div>
        </ul>
    </div>
</div>

<!-- Комментарии -->
{% include 'comments/comments.html' with publication=publication comments=publication.comments.all%}


{% endblock %}

publications/templates/publications/publication_form.html
{% extends 'base/base.html' %}
{% block title %}
{% if object %}
Изменить публикацию
{% else %}
Создать публикацию
{% endif %}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>

                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        {% if object %}
                        <a class="btn btn-outline-primary px-2 pb-md-2 mx-2"
                           href="{% url 'publications:publication_view' pk=object.pk %}"
                           role="button">Назад</a>
                        <button type="submit" class="btn btn-outline-success ml-5 px-2 pb-md-2 mx-2" role="button">
                            Сохранить
                        </button>
                        {% else %}
                        <a class="btn btn-outline-primary px-2 pb-md-2 mx-2"
                           href="{% url 'publications:publication_list' %}"
                           role="button">Назад</a>
                        <button type="submit" class="btn btn-outline-success ml-5 px-2 pb-md-2 mx-2" role="button">
                            Создать
                        </button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

publications/templates/publications/publication_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load my_tags %}
{% block title %}Список публикаций{% endblock title %}
{% block content %}

<!-- Основные публикации со ссылками -->
<div class="row g-5">

    <!-- Публикации -->
    <div class="col-md-12">
        <h3 class="pb-4 mb-4 fst-italic border-bottom text-center">
            {% if title == 'Мои публикации' %}
            Мои публикации
            {% else %}
            Публикации
            {% endif %}
        </h3>

        {% for object in object_list %}
        <!-- для пагинации -->
        {{ object.full_name|upper }}<br>
        <!-- Карточка публикации -->
        <div class="card mb-4">
            <div class="card-header">
                <!-- Заголовок -->
                <h4 class="card-title">{{ object.title }}</h4>

                <!-- Мета данные -->
                <ul class="list-group list-group-horizontal">
                    {% if object.author.avatar %}
                    <img class="img-fluid" src="{{ object.author.avatar | media_filter}}" width="40px">
                    {% endif %}
                    <li class="list-group-item">
                        {{ object.author.nickname }}
                    </li>
                    <li class="list-group-item">
                        {{object.created_at}}
                    </li>
                    {% if object.is_paid %}
                    <li class="list-group-item">
                        <img class="img-fluid" src="{% static 'img/paid_publication.png' %}" width="30px">
                    </li>
                    {% endif %}
                </ul>
            </div>

            <!-- Содержание публикации -->
            <div class="card-body">
                <!-- Изображение -->
                {% if object.preview %}
                <img src="{{ object.preview | media_filter}}" class="figure-img img-fluid rounded" width="400px">
                {% endif %}
                <p class="card-text">{{ object.body | truncatechars:100 }}</p>

                <!-- ссылка делает всю карточку кликабельной -->
                <a href="{% url 'publications:publication_view' object.pk %}"
                   class="icon-link gap-1 icon-link-hover stretched-link">
                    Подробнее
                </a>

            </div>
            <div class="card-footer">
                <!-- Отображение просмотров и лайков -->
                <p class="card-text">
                    <small class="text-body-secondary">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <img class="img-fluid" src="{% static 'img/views.png' %}" width="25px">
                                <b>{{ object.views_count }}</b>
                            </li>
                            <li class="list-inline-item">
                                <img class="img-fluid" src="{% static 'img/likes.png' %}" width="20px">
                                <b>{{ object.liked_by.all.count }}</b>
                            </li>
                        </ul>
                    </small>
                </p>
            </div>
        </div>

        <hr>
        {% endfor %}

        <!-- Пагинация -->
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; На первую</a>
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">На последнюю &raquo;</a>
                {% endif %}
            </span>
        </div>
        <hr>
    </div>
</div>

{% endblock %}