base/urls.py
from django.urls import path

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "", include("publications.urls", namespace="publications")
    ),  # маршрутизация к публикациям
    path(
        "users/", include("users.urls", namespace="users")
    ),  # маршрутизация к пользователям
    path(
        "comments/", include("comments.urls", namespace="comments")
    ),  # маршрутизация к комментариям
    path(
        "codes/", include("codes.urls", namespace="codes")
    ),  # маршрутизация к кодам верификации
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path

from publications.apps import PublicationsConfig
from publications.views import (
    PublicationListView,
    PublicationDetailView,
    PublicationCreateView,
    PublicationUpdateView,
    PublicationDeleteView,
    AddRemoveLike,
    PublicationOwnerListView,
)

app_name = PublicationsConfig.name

urlpatterns = [
    path(
        "", PublicationListView.as_view(), name="publication_list"
    ),  # список публикаций
    path(
        "owner_pub/", PublicationOwnerListView.as_view(), name="owner_pub"
    ),  # вывод списка собственных публикаций
    path(
        "view/<int:pk>/", PublicationDetailView.as_view(), name="publication_view"
    ),  # просмотр одной публикации
    path(
        "create/", PublicationCreateView.as_view(), name="publication_create"
    ),  # создание публикации
    path(
        "update/<int:pk>/",
        PublicationUpdateView.as_view(),
        name="publication_update",
    ),  # редактирование публикации
    path(
        "delete/<int:pk>/",
        PublicationDeleteView.as_view(),
        name="publication_delete",
    ),  # удаление публикации
    path(
        "<int:pk>/like/", AddRemoveLike.as_view(), name="like"
    ),  # установить/удалить лайк
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from django.contrib.auth.views import LogoutView

from users.views import UserCreateView, UserLoginView, PaidSubscriptionCreateView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),  # вход
    path("logout/", LogoutView.as_view(), name="logout"),  # выход
    path("register/", UserCreateView.as_view(), name="register"),  # регистрация
    # оплата подписки
    path(
        "paid_subscription/",
        PaidSubscriptionCreateView.as_view(),
        name="paid_subscription",
    ),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

base/templates/base/includes/inc_menu.html
<!-- Основное меню -->
<div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'publications:owner_pub' %}">Мои публикации</a>
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'publications:publication_create' %}">
            Создать публикацию
        </a>
        {% endif %}
    </nav>
</div>

base/templates/base/includes/inc_registrations_and_title.html
<!-- Название с регистрацией и подспиской -->
{% load my_tags %}

<header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            {% if user.is_authenticated %}
                {% if user.is_sub %}
                    Вы подписаны на платные публикации
                {% else %}
                    <a class="link-secondary" href="{% url 'users:paid_subscription'%}">Подписаться</a>
                {% endif %}
            {% endif %}
        </div>
        <div class="col-4 text-center">
            <a class="blog-header-logo text-body-emphasis text-decoration-none"
               href="{% url 'publications:publication_list' %}">Хочу все знать</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            {% if user.is_authenticated %}
                <ul class="list-group list-group-horizontal ">
                    <li class="list-group-item">
                        <a href="{% url 'users:logout' %}" class="btn">Выйти</a>
                    </li>

                    {% if user.avatar %}
                    <img class="img-fluid" src="{{ user.avatar | media_filter}}" width="50px">
                    {% endif %}

                    <li class="list-group-item align-middle">
                        <span>{{ user.nickname }}</span>
                    </li>
                </ul>
            {% else %}
            <a href="{% url 'users:login' %}" class="btn btn-sm btn-outline-secondary">Войти</a>
            <a href="{% url 'users:register' %}" class="btn btn-sm btn-outline-secondary">Регистрация</a>
            {% endif %}
        </div>
    </div>
</header>